version: "3.8"
services:
  frontend:
    build:
      context: ./durmitor-frontend
    ports:
      - 3000:3000
    networks:
      - durmitor
  admin:
    build:
      context: ./black-lake
      dockerfile: Dockerfile
    command: "php artisan serve --host=0.0.0.0"
    volumes:
      - black-lake:/app
    ports:
      - 8000:8000
    depends_on:
      - admin_db
    networks:
      - durmitor
  admin_db:
    image: mysql:5.7.22
    environment:
      MYSQL_DATABASE: admin
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./black-lake/storage/dbdata:/var/lib/mysql
    ports:
      - 33063:3306
    networks:
      - durmitor
volumes:
  black-lake:

networks:
  durmitor:
    driver: bridge
